const LINE_URL = "https://lin.ee/5QwrADp";

const products = [
  {
    id: "dior-cushion",
    group: "dior",
    recommended: true,
    name: "DIOR Flowery Bow 玫瑰限量氣墊",
    spec: "1 殼 1 蕊",
    originalPrice: 3050,
    salePrice: 2880,
    timing: "預購｜8 月底前",
    tags: ["本週主打", "限量外殼", "收藏款"],
    image: "dior-flowery-bow.jpg",
    highlight: "限量高訂外殼、白色玫瑰蝴蝶結收藏款",
    description: "白色玫瑰款清新、優雅、不甜膩，很適合喜歡乾淨感、法式感、精品小物感的人。",
    lineMessage: "我要詢問：DIOR Flowery Bow 玫瑰限量氣墊，款式色號：柔霧 / 水光"
  },
  {
    id: "sabon-scrub-600",
    group: "sabon",
    recommended: true,
    name: "SABON 熱帶果嶼身體磨砂膏",
    spec: "600ml",
    originalPrice: 2180,
    salePrice: 1580,
    timing: "8/21 上市｜預購約 9 月底到",
    tags: ["夏日推薦", "明星品", "公司貨"],
    image: "sabon-body-scrub.jpg",
    highlight: "SABON 經典明星品、夏日果香去角質",
    description: "SABON 經典明星品，去角質同時留下熱帶果香。",
    lineMessage: "我要下單：SABON 熱帶果嶼身體磨砂膏 600ml"
  },
  {
    id: "jo-cologne",
    group: "jo",
    recommended: true,
    name: "Jo Malone 限量英倫田園香水",
    spec: "30ml",
    originalPrice: 3100,
    salePrice: 2380,
    timing: "預購｜7/6 上市｜預計 8 月底出貨",
    tags: ["限量系列", "不撞香", "公司貨"],
    image: "jo-malone-garden-hero.jpg",
    highlight: "限量蔬果香氛、乾淨綠意感、不撞香",
    description: "清新田園感香氣，有記憶點又不會太甜膩。",
    lineMessage: "我要詢問：Jo Malone 限量英倫田園香水 30ml"
  },
  {
    id: "sabon-kit",
    group: "sabon",
    recommended: true,
    name: "SABON 熱帶果嶼明星三部曲推薦組",
    spec: "組合",
    originalPrice: 1280,
    salePrice: 930,
    timing: "7/23 上市｜預購約 8 月底到",
    tags: ["入門推薦", "送禮自用", "公司貨"],
    image: "sabon-welcome-kit.jpg",
    highlight: "第一次入手 SABON 很適合",
    description: "一次收齊人氣三步驟，送禮自用都很適合。",
    lineMessage: "我要下單：SABON 熱帶果嶼明星三部曲推薦組"
  },
  {
    id: "jo-candle-300",
    group: "jo",
    recommended: true,
    name: "Jo Malone 綠番茄藤陶瓷蠟燭",
    spec: "300g",
    originalPrice: 5200,
    salePrice: 3980,
    timing: "預購｜7/6 上市｜預計 8 月底出貨",
    tags: ["收藏款", "居家香氛", "公司貨"],
    image: "jo-green-tomato-candle.jpg",
    highlight: "收藏款、居家香氛、質感擺設",
    description: "大容量陶瓷蠟燭，收藏感與擺設感都很強。",
    lineMessage: "我要下單：Jo Malone 綠番茄藤陶瓷蠟燭 300g"
  },
  {
    id: "sabon-oil-500",
    group: "sabon",
    name: "熱帶果嶼輕潤沐浴油",
    spec: "500ml",
    originalPrice: 1380,
    salePrice: 990,
    timing: "7/23 上市｜預購約 8 月底到",
    tags: ["預購", "限量系列"],
    image: "sabon-shower-oil-500.jpg",
    description: "清潔同時保有柔潤膚觸，洗完像把夏日果香留在肌膚上。",
    lineMessage: "我要下單：SABON 熱帶果嶼輕潤沐浴油 500ml"
  },
  {
    id: "sabon-oil-300",
    group: "sabon",
    name: "熱帶果嶼輕潤沐浴油",
    spec: "300ml",
    originalPrice: 1080,
    salePrice: 790,
    timing: "7/23 上市｜預購約 8 月底到",
    tags: ["預購", "入門容量"],
    image: "sabon-shower-oil-500.jpg",
    description: "輕巧容量更適合第一次入手，清爽果香日常也很好用。",
    lineMessage: "我要下單：SABON 熱帶果嶼輕潤沐浴油 300ml"
  },
  {
    id: "sabon-hand-cream",
    group: "sabon",
    name: "熱帶果嶼護手霜",
    spec: "30ml",
    originalPrice: 420,
    salePrice: 320,
    timing: "7/23 上市｜預購約 8 月底到",
    tags: ["隨身補香", "公司貨"],
    image: "sabon-hand-cream-30.jpg",
    description: "隨身補香補潤的小可愛，清甜果香剛剛好。",
    lineMessage: "我要下單：SABON 熱帶果嶼護手霜 30ml"
  },
  {
    id: "sabon-gelee",
    group: "sabon",
    name: "熱帶果嶼清爽保濕凝凍",
    spec: "200ml",
    originalPrice: 1580,
    salePrice: 1150,
    timing: "8/14 上市｜預購約 9 月底到",
    tags: ["清爽保濕", "夏日推薦"],
    image: "sabon-body-gelee-200.jpg",
    description: "夏天最適合的清爽保濕感，擦完肌膚嫩嫩香香的。",
    lineMessage: "我要下單：SABON 熱帶果嶼清爽保濕凝凍 200ml"
  },
  {
    id: "sabon-scrub-320",
    group: "sabon",
    name: "熱帶果嶼身體磨砂膏",
    spec: "320ml",
    originalPrice: 1580,
    salePrice: 1150,
    timing: "8/21 上市｜預購約 9 月底到",
    tags: ["預購", "入門容量"],
    image: "sabon-body-scrub.jpg",
    description: "喜歡磨砂膏但想先小容量入手的人很適合。",
    lineMessage: "我要下單：SABON 熱帶果嶼身體磨砂膏 320ml"
  },
  {
    id: "jo-carrot",
    group: "jo",
    name: "蕾絲胡蘿蔔花香水",
    spec: "30ml",
    originalPrice: 3100,
    salePrice: 2380,
    timing: "預購｜7/6 上市｜預計 8 月底出貨",
    tags: ["限量系列", "田園香氣"],
    image: "jo-carrot-blossom.jpg",
    description: "清新花香中帶一點自然綠意，溫柔又很有田園感。",
    lineMessage: "我要下單：Jo Malone 蕾絲胡蘿蔔花香水 30ml"
  },
  {
    id: "jo-beetroot",
    group: "jo",
    name: "緋紅甜菜根香水",
    spec: "30ml",
    originalPrice: 3100,
    salePrice: 2380,
    timing: "預購｜7/6 上市｜預計 8 月底出貨",
    tags: ["限量系列", "不撞香"],
    image: "jo-scarlet-beetroot.jpg",
    description: "帶點甜潤、微微泥土感的蔬果香氣，很特別不撞香。",
    lineMessage: "我要下單：Jo Malone 緋紅甜菜根香水 30ml"
  },
  {
    id: "jo-butternut",
    group: "jo",
    name: "絲絨奶油南瓜香水",
    spec: "30ml",
    originalPrice: 3100,
    salePrice: 2380,
    timing: "預購｜7/6 上市｜預計 8 月底出貨",
    tags: ["限量系列", "暖甜感"],
    image: "jo-velvety-butternut.jpg",
    description: "柔和溫暖的奶油南瓜香，舒服、可愛又帶一點暖甜感。",
    lineMessage: "我要下單：Jo Malone 絲絨奶油南瓜香水 30ml"
  },
  {
    id: "jo-hand-wash",
    group: "jo",
    name: "番茄葉手部清潔露",
    spec: "250ml",
    originalPrice: 2050,
    salePrice: 1580,
    timing: "預購｜7/6 上市｜預計 8 月底出貨",
    tags: ["可作沐浴露", "綠意香氣"],
    image: "jo-tomato-leaf-wash.jpg",
    description: "可做沐浴露使用，番茄葉香氣清爽有綠意，洗完很乾淨舒服。",
    lineMessage: "我要下單：Jo Malone 番茄葉手部清潔露 250ml"
  },
  {
    id: "jo-candle-75",
    group: "jo",
    name: "綠番茄藤陶瓷蠟燭",
    spec: "75g",
    originalPrice: 2000,
    salePrice: 1550,
    timing: "預購｜7/6 上市｜預計 8 月底出貨",
    tags: ["小容量收藏", "居家香氛"],
    image: "jo-green-tomato-candle.jpg",
    description: "小容量收藏款，適合想先入手綠意香氛的人。",
    lineMessage: "我要下單：Jo Malone 綠番茄藤陶瓷蠟燭 75g"
  }
];

const needs = [
  { title: "想找身體保養", items: ["SABON 沐浴油", "SABON 磨砂膏", "SABON 保濕凝凍", "SABON 護手霜"] },
  { title: "想找香水", items: ["Jo Malone 蕾絲胡蘿蔔花香水", "Jo Malone 緋紅甜菜根香水", "Jo Malone 絲絨奶油南瓜香水"] },
  { title: "想找居家香氛", items: ["Jo Malone 綠番茄藤陶瓷蠟燭 75g", "Jo Malone 綠番茄藤陶瓷蠟燭 300g"] },
  { title: "想找精品彩妝", items: ["DIOR Flowery Bow 玫瑰限量氣墊"] }
];
